/**
 * Banco curado de receitas fitness brasileiras.
 * Categorizado por objetivo: lose (emagrecer), gain (ganhar massa), all (qualquer).
 */
export interface FitnessRecipe {
  id: string;
  name: string;
  emoji: string;
  category: "café" | "almoço" | "jantar" | "lanche" | "pré-treino" | "pós-treino";
  goal: "lose" | "gain" | "all";
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: number; // minutos
  ingredients: string[];
  steps: string[];
}

export const FITNESS_RECIPES: FitnessRecipe[] = [
  {
    id: "panqueca-banana",
    name: "Panqueca proteica de banana",
    emoji: "🥞",
    category: "café",
    goal: "all",
    calories: 320,
    protein: 28,
    carbs: 38,
    fat: 6,
    prepTime: 10,
    ingredients: ["1 banana madura", "2 ovos", "30g whey baunilha", "1 col. sopa aveia", "canela a gosto"],
    steps: [
      "Amasse a banana com um garfo.",
      "Misture os ovos, whey, aveia e canela até virar massa lisa.",
      "Despeje em frigideira antiaderente em fogo baixo.",
      "Vire quando bordas firmarem (~2 min cada lado).",
    ],
  },
  {
    id: "omelete-frango",
    name: "Omelete de frango e queijo",
    emoji: "🍳",
    category: "café",
    goal: "gain",
    calories: 410,
    protein: 38,
    carbs: 4,
    fat: 26,
    prepTime: 12,
    ingredients: ["3 ovos", "60g frango desfiado", "30g queijo minas", "salsinha", "sal e pimenta"],
    steps: [
      "Bata os ovos com sal e pimenta.",
      "Aqueça a frigideira em fogo médio com pouco azeite.",
      "Despeje os ovos, espalhe o frango e o queijo no centro.",
      "Dobre ao meio quando firmar e finalize com salsinha.",
    ],
  },
  {
    id: "iogurte-frutas",
    name: "Iogurte com granola e frutas vermelhas",
    emoji: "🍓",
    category: "café",
    goal: "lose",
    calories: 240,
    protein: 18,
    carbs: 30,
    fat: 4,
    prepTime: 3,
    ingredients: ["180g iogurte natural desnatado", "30g granola sem açúcar", "100g morangos", "1 col. chá mel"],
    steps: ["Em uma taça, coloque o iogurte.", "Adicione granola e morangos por cima.", "Finalize com mel."],
  },
  {
    id: "frango-batata-doce",
    name: "Frango grelhado com batata-doce",
    emoji: "🍗",
    category: "almoço",
    goal: "all",
    calories: 480,
    protein: 45,
    carbs: 50,
    fat: 8,
    prepTime: 25,
    ingredients: ["150g peito de frango", "200g batata-doce", "salada verde à vontade", "azeite, alho, limão"],
    steps: [
      "Tempere o frango com alho, limão, sal e pimenta — deixe descansar 10 min.",
      "Cozinhe a batata-doce na água ou asse no forno.",
      "Grelhe o frango ~5 min de cada lado.",
      "Sirva com salada regada com fio de azeite.",
    ],
  },
  {
    id: "salmao-quinoa",
    name: "Salmão com quinoa e brócolis",
    emoji: "🐟",
    category: "almoço",
    goal: "all",
    calories: 540,
    protein: 40,
    carbs: 42,
    fat: 22,
    prepTime: 30,
    ingredients: ["140g salmão", "60g quinoa seca", "150g brócolis", "limão, alho, azeite"],
    steps: [
      "Cozinhe a quinoa conforme embalagem.",
      "Tempere o salmão com sal, alho e limão.",
      "Asse o salmão por 15 min a 200°C.",
      "Refogue o brócolis no alho e azeite.",
      "Monte o prato e regue com limão.",
    ],
  },
  {
    id: "wrap-frango",
    name: "Wrap integral de frango",
    emoji: "🌯",
    category: "almoço",
    goal: "lose",
    calories: 380,
    protein: 32,
    carbs: 35,
    fat: 12,
    prepTime: 15,
    ingredients: ["1 tortilha integral", "120g frango desfiado", "alface, tomate, cenoura ralada", "1 col. sopa iogurte natural"],
    steps: [
      "Aqueça a tortilha por 30s na frigideira.",
      "Misture o iogurte com pitada de páprica.",
      "Espalhe sobre a tortilha, adicione o frango e os vegetais.",
      "Enrole firme e corte ao meio.",
    ],
  },
  {
    id: "carne-arroz-integral",
    name: "Patinho com arroz integral e legumes",
    emoji: "🥩",
    category: "jantar",
    goal: "gain",
    calories: 620,
    protein: 48,
    carbs: 60,
    fat: 18,
    prepTime: 25,
    ingredients: ["150g patinho moído", "80g arroz integral seco", "abobrinha, cenoura, vagem", "alho, cebola, azeite"],
    steps: [
      "Cozinhe o arroz integral.",
      "Refogue alho e cebola, adicione a carne moída.",
      "Acrescente os legumes em cubos pequenos e cozinhe até al dente.",
      "Sirva o arroz com o refogado por cima.",
    ],
  },
  {
    id: "sopa-frango",
    name: "Sopa de frango com legumes",
    emoji: "🍲",
    category: "jantar",
    goal: "lose",
    calories: 290,
    protein: 30,
    carbs: 22,
    fat: 8,
    prepTime: 30,
    ingredients: ["120g frango desfiado", "1 batata pequena", "cenoura, abobrinha, chuchu", "caldo caseiro, salsinha"],
    steps: [
      "Refogue alho e cebola em panela.",
      "Adicione o frango e doure ligeiramente.",
      "Acrescente os legumes em cubos e cubra com água/caldo.",
      "Cozinhe ~20 min até ficar macio. Finalize com salsinha.",
    ],
  },
  {
    id: "ovos-mexidos-pao",
    name: "Ovos mexidos com pão integral",
    emoji: "🍞",
    category: "jantar",
    goal: "all",
    calories: 360,
    protein: 24,
    carbs: 30,
    fat: 16,
    prepTime: 10,
    ingredients: ["3 ovos", "2 fatias pão integral", "1 col. chá manteiga", "cebolinha"],
    steps: [
      "Bata os ovos levemente com pitada de sal.",
      "Em fogo baixo, derreta a manteiga e despeje os ovos.",
      "Mexa devagar até cremoso.",
      "Sirva sobre o pão torrado com cebolinha por cima.",
    ],
  },
  {
    id: "smoothie-proteico",
    name: "Smoothie proteico de morango",
    emoji: "🥤",
    category: "lanche",
    goal: "all",
    calories: 280,
    protein: 30,
    carbs: 28,
    fat: 4,
    prepTime: 3,
    ingredients: ["30g whey morango", "200ml leite desnatado", "100g morangos", "5 cubos de gelo"],
    steps: ["Coloque tudo no liquidificador.", "Bata por 30 segundos.", "Sirva imediatamente."],
  },
  {
    id: "mix-castanhas",
    name: "Mix de castanhas e frutas secas",
    emoji: "🥜",
    category: "lanche",
    goal: "gain",
    calories: 250,
    protein: 7,
    carbs: 18,
    fat: 17,
    prepTime: 1,
    ingredients: ["20g castanha de caju", "15g amêndoas", "2 damascos secos", "1 col. sopa uva passa"],
    steps: ["Misture tudo em um pote.", "Pronto para levar na bolsa ou mochila."],
  },
  {
    id: "tapioca-frango",
    name: "Tapioca recheada com frango",
    emoji: "🫓",
    category: "lanche",
    goal: "all",
    calories: 320,
    protein: 26,
    carbs: 30,
    fat: 10,
    prepTime: 12,
    ingredients: ["3 col. sopa goma de tapioca", "100g frango desfiado", "1 fatia queijo branco", "salsinha"],
    steps: [
      "Espalhe a goma na frigideira quente até virar disco.",
      "Recheie com frango e queijo.",
      "Dobre ao meio e finalize com salsinha.",
    ],
  },
  {
    id: "banana-pasta-amendoim",
    name: "Banana com pasta de amendoim",
    emoji: "🍌",
    category: "pré-treino",
    goal: "all",
    calories: 220,
    protein: 6,
    carbs: 30,
    fat: 9,
    prepTime: 2,
    ingredients: ["1 banana", "1 col. sopa pasta de amendoim integral", "canela"],
    steps: ["Corte a banana em rodelas.", "Espalhe a pasta por cima e polvilhe canela."],
  },
  {
    id: "aveia-mel",
    name: "Mingau de aveia com mel e banana",
    emoji: "🥣",
    category: "pré-treino",
    goal: "gain",
    calories: 380,
    protein: 12,
    carbs: 65,
    fat: 7,
    prepTime: 8,
    ingredients: ["50g aveia em flocos", "200ml leite", "1 banana", "1 col. sopa mel", "canela"],
    steps: [
      "Aqueça o leite em fogo baixo.",
      "Adicione a aveia mexendo até engrossar (~5 min).",
      "Sirva com banana fatiada, mel e canela.",
    ],
  },
  {
    id: "shake-pos-treino",
    name: "Shake recovery pós-treino",
    emoji: "💪",
    category: "pós-treino",
    goal: "gain",
    calories: 340,
    protein: 35,
    carbs: 40,
    fat: 3,
    prepTime: 3,
    ingredients: ["30g whey isolado", "1 banana", "300ml água ou leite desnatado", "1 col. sopa aveia"],
    steps: ["Bata tudo no liquidificador por 30s.", "Tome em até 30 min após o treino."],
  },
  {
    id: "iogurte-whey",
    name: "Iogurte proteico pós-treino",
    emoji: "🥛",
    category: "pós-treino",
    goal: "lose",
    calories: 200,
    protein: 30,
    carbs: 14,
    fat: 2,
    prepTime: 2,
    ingredients: ["200g iogurte grego desnatado", "15g whey baunilha", "1 col. sopa chia"],
    steps: ["Misture o whey ao iogurte até dissolver.", "Polvilhe a chia por cima."],
  },
];

export function getRecipesByGoal(goal: string): FitnessRecipe[] {
  if (!goal || goal === "all") return FITNESS_RECIPES;
  return FITNESS_RECIPES.filter((r) => r.goal === goal || r.goal === "all");
}
