project_id = "csikbgwayqhgnuveidaz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-portal-session]
    verify_jwt = false
  [functions.get-maps-key]
    verify_jwt = false
  [functions.get-stripe-price]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.abacatepay-webhook]
    verify_jwt = false
  [functions.seed-exercise-library]
    verify_jwt = false


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1